version: "3.9"

services:
  crud:
    image: postgres
    container_name: labelx_backend
    restart: always
    ports:
      - 5666:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local